name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    # Enable Windows targeting globally for the entire job
    # This allows .NET SDK to restore Windows-specific packages on Linux
    env:
      EnableWindowsTargeting: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_XMLDOC_MODE: skip

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache restoration happens BEFORE installing SDKs and tools
      # This way we can skip installations if everything is cached
      - name: Cache NuGet packages
        id: cache-nuget
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props', '**/Directory.Build.props', 'global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Cache .NET tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('.github/workflows/copilot-setup-steps.yml') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-tools-

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'ga'

      - name: Setup .NET 8 SDK (for compatibility)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Install dotnet tools
        # Only install if cache wasn't hit
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          # Install code formatting and analysis tools
          dotnet tool install --global dotnet-format || true
          dotnet tool install --global dotnet-reportgenerator-globaltool || true
          
          # Install XamlStyler for XAML formatting (used in the project)
          dotnet tool install --global XamlStyler.Console || true
          
          # Install C# script runner for quick code execution
          dotnet tool install --global dotnet-script || true
          
          echo "Installed dotnet tools:"
          dotnet tool list --global

      - name: Setup C# compiler (csc)
        run: |
          # Create convenient aliases for the C# compiler
          # The Roslyn compiler is included with the .NET SDK
          
          # Find the Roslyn compiler location
          ROSLYN_PATH=$(find ~/.dotnet/sdk -name "csc.dll" | head -1)
          ROSLYN_DIR=$(dirname "$ROSLYN_PATH")
          
          if [ -n "$ROSLYN_PATH" ]; then
            echo "Found Roslyn compiler at: $ROSLYN_PATH"
            
            # Create a wrapper script for csc
            cat > ~/.local/bin/csc << EOF
          #!/bin/bash
          exec dotnet "$ROSLYN_PATH" "\$@"
          EOF
            chmod +x ~/.local/bin/csc
            
            # Also create csi (C# Interactive) wrapper
            CSI_PATH="$ROSLYN_DIR/csi.dll"
            if [ -f "$CSI_PATH" ]; then
              cat > ~/.local/bin/csi << EOF
          #!/bin/bash
          exec dotnet "$CSI_PATH" "\$@"
          EOF
              chmod +x ~/.local/bin/csi
              echo "Created csi (C# Interactive) wrapper"
            fi
            
            # Ensure ~/.local/bin is in PATH
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.profile
            
            # Add to current session
            export PATH="$HOME/.local/bin:$PATH"
            
            echo "C# compiler setup complete. Available commands:"
            echo "  csc - C# compiler"
            echo "  csi - C# Interactive REPL (if available)"
            echo "  dotnet-script - C# scripting with NuGet support"
          else
            echo "Warning: Could not find Roslyn compiler in .NET SDK"
          fi
          
          # Create directory if it doesn't exist
          mkdir -p ~/.local/bin
      
      - name: Restore NuGet packages
        run: |
          echo "Restoring packages..."
          
          # EnableWindowsTargeting is set in Directory.Build.props
          # This allows restoration of Windows-specific packages on Linux
          dotnet restore --ignore-failed-sources || true
          
          echo "Package restore completed."
          echo "Note: C++ projects (.vcxproj) will still show warnings - this is expected."
          
      - name: Verify configuration
        run: |
          echo "=== Verification of setup ==="
          
          # Test that we can build a simple Windows-targeted project
          echo "Testing Windows targeting..."
          cat > test-windows-targeting.csproj << 'EOF'
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>net9.0-windows</TargetFramework>
              <OutputType>Library</OutputType>
            </PropertyGroup>
          </Project>
          EOF
          
          if dotnet build test-windows-targeting.csproj --no-restore 2>/dev/null; then
            echo "✓ Windows targeting is working correctly!"
          else
            echo "⚠ Windows targeting test failed, but this is expected for some configurations"
          fi
          
          rm -f test-windows-targeting.csproj
          
          # Test C# compiler
          echo ""
          echo "Testing C# compiler..."
          cat > test.cs << 'EOF'
          using System;
          class Program {
              static void Main() {
                  Console.WriteLine("C# compiler is working!");
              }
          }
          EOF
          
          # Update PATH for this session
          export PATH="$HOME/.local/bin:$PATH"
          
          if command -v csc &> /dev/null; then
            if csc test.cs -out:test.exe 2>/dev/null; then
              echo "✓ csc (C# compiler) is working!"
            else
              echo "⚠ csc found but compilation test failed"
            fi
          else
            echo "⚠ csc command not found in PATH"
          fi
          
          if command -v dotnet-script &> /dev/null; then
            echo "✓ dotnet-script is available for C# scripting"
          fi
          
          rm -f test.cs test.exe
          
          echo ""
          echo "=== Available C# tools ==="
          echo "PATH: $PATH"
          ls -la ~/.local/bin/ 2>/dev/null || echo "No custom binaries in ~/.local/bin"
          
          echo ""
          echo "=== Directory.Build.props content ==="
          cat Directory.Build.props

      - name: Install development utilities
        run: |
          # Install useful utilities for code analysis and development
          sudo apt-get update
          sudo apt-get install -y \
            jq \
            tree \
            ripgrep \
            fd-find

      - name: Setup environment variables
        run: |
          # Set up any environment variables that might be useful
          echo "DOTNET_NOLOGO=true" >> $GITHUB_ENV
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
          echo "NUGET_XMLDOC_MODE=skip" >> $GITHUB_ENV
          
      - name: Display project information
        run: |
          echo "=== Project Structure ==="
          tree -d -L 2 src/ || true
          
          echo ""
          echo "=== .NET SDKs installed ==="
          dotnet --list-sdks
          
          echo ""
          echo "=== .NET Runtimes installed ==="
          dotnet --list-runtimes
          
          echo ""
          echo "=== Project files ==="
          find . -name "*.csproj" -o -name "*.slnx" -o -name "*.wapproj" | head -20

      - name: Create Copilot helper scripts
        run: |
          # Create a script to help Copilot understand the project structure
          cat > /tmp/copilot-project-info.sh << 'EOF'
          #!/bin/bash
          echo "This is a Windows Files application project."
          echo "Main components:"
          echo "- Files.App: Main application (Windows-specific)"
          echo "- Core libraries: May contain cross-platform compatible code"
          echo ""
          echo "Note: This project is primarily Windows-targeted."
          echo "Full builds require Windows and Visual Studio/MSBuild."
          echo "On Linux, only basic .NET SDK operations are available."
          EOF
          chmod +x /tmp/copilot-project-info.sh
          
          echo "Created helper script at /tmp/copilot-project-info.sh"